sudo: required
dist: trusty
language: node_js
node_js:
- '7'
before_install:
- npm install -g npm
- npm install -g kaba-cli
before_script:
- kaba js
addons:
  browserstack:
    username: kaieichinger1
    access_key:
      secure: ~
env:
  global:
    secure: ZINJToarnlq2gqnlvAY2v/ClGWIu93+5DYl/kpjmivCCc8LojKo6C60wxziC/4TFEQVYqWbNc09EL8fXd8W+pchsQvEcCNl9id7BXgtWeSzDY5SAR2No84FzorqPHBEyuCM58pQGkan7B883+fSAL+zV++FTsqwLzNucOli6ddYE3ihY29Z0Pw3mvjqWLEWGgqxhrRcq8gCYgcJS3VLCk91CwDOtnXgH7tTPQYPncCiTu5NDhOPkEX1oPQQorZHQWUL8mdAvJU43qEGlUFvx9GqcNzOnTu5SXojFEaP7smQpwK9V+oMUqrZCirv3pU5eSLxPBINpQdB4g45IY7Sw7ckx58ROJ6N3ZNsZlNG2XViLfxYvTPFxgCZSEOSa2+lbruhv2HR5YMRXQz+DxkPmyZKrjHym/u4pptA2TQjl3iASykkbFHpuzGTgZLcPRWJW2y++oPCmL3GUOlVKTzSZjrxnjd6Xa+6z1gPUxNbp1tW0+hyT2k8nxdtzn3060kmpc00HDqgo7ibruXtKxnXSkunucSi9pV+T62pVqDdalCdeo1qmQhnxqlU5GrJjaTlXKbJarcOQ6I+8xbMQJZhHBLxZJ6ZqjFH8enbBy+/y1OZev2m9JPgcPBpuphuLpA03HUvZB/TM8oGct6vecvuufJRFNuOgbEnHLhSEDFtn3Ls=
