sudo: required
dist: trusty
language: node_js
node_js:
- '7'
before_install:
- npm install -g npm
- npm install -g kaba-cli
before_script:
- kaba js
- [[ -n "$CI_BROWSERSTACK_USER" ]] && export BROWSERSTACK_USER="$CI_BROWSERSTACK_USER"
- [[ -n "$CI_BROWSERSTACK_ACCESS_KEY" ]] && export BROWSERSTACK_ACCESS_KEY="$CI_BROWSERSTACK_ACCESS_KEY"
addons:
  browserstack:
    username: "kaieichinger1"
    access_key:
      secure: "TttpzJnujhBf4z2wK05zOLSGhw0i1SD4ExDWqBVh1uAjw8hMjduVL05mFfwQzh8fHmzgZwnxnyITY9oGjVbdIEqrRVokDqf+C+o43O4o+SiOGWM1nR9u0iWWqQBawHR4K/9D2bD9Wm7LQjvfXHkBUqtexYrTu1iVXyCfUT0wrY4kFpVkHwaeJRdKVjZOANERRUrh03ezO56Echfq45uUzg8TkwnzRXQ1nH4XAHLhfjCA0A8id4LnMoIinQf38AT4tKJwk39GaZZbxk2SXQu2rcQ8C952aXM5aGt7/bqFzZt/bmLMpyhYFbXAaJ3EuKW1I4kIOGNLSxxTzv8g+gdu4yf5WcCxdEiQCbnp7GOmXrexG94W5TJXlXlKXZXvq5GXdQJdJC8jvCSMqJUN8hv4NxKb+we1bx/qtcHk4DlcJm2MbjitlKreyiV144X508sOxDpiqZ+PXVIn1r1tes6HXO1FYE8Ell1gB49EFdX5tRYgyY/zqaFBeq9jDpzeU9u87WcgUUTgkZfXfZkapM/k/DA/dYL4raXdFpqb4QeP0XzJ+kuUBVXwMl3LTVkytJY2htMK55VFkpfOlve5OG/nMuUEe/jmNaoBTnSL09lMVzLfG1Fjk8MzMh7zIvXJLaD9WuAN8Jvz4t/eKW+d+hiUCGmSU0rH/V55ptKopvWCk0M="
